# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
    region                  = "us-east-1"
    shared_credentials_file = "~/.aws/credentials"
    profile                 = "default"
}
