# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tr-bucket-kr-v"
    dynamodb_table = "terraform-state-lock-dynamo"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
